[package]
name = "secview"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "secviewlib"
path = "src/lib.rs"

[[bin]]
name = "secviewbin"
path = "src/bin.rs"

[dependencies]
screenshots = "0.8.10"
